### ISSUE TITLE
Add post-install chart hook to m2k instead of manual stesp

### ISSUE THREAD

**Issue by masayag** [parodos-dev/serverless-workflows-config#118]
Currently, installing the m2k helm chart asks the user for follow-up steps to complete the installation and configuration of the m2k workflow.
This can be leveraged by the helm chart hook of type post-install.

**Comment by gabriel-farache** [comment]
@masayag now there is a script to install the workflow, same for MTA, would that fulfill your needs?

**Comment by masayag** [comment]
but those aren't my needs, it is a user's needs :-)

**Comment by gabriel-farache** [comment]
> but those aren't my needs, it is a user's needs :-)

you're the owner of the issue, so it's your needs, as a user :p
